package com.acme.banksolution.advice;

import com.acme.banksolution.bean.ErrorBean;
import com.acme.banksolution.exception.AcmeException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.context.request.WebRequest;

/**
 * This class handles all the Exception generated by service layer and sends a predefined response to API caller
 *
 * @author VKumar
 */
@ControllerAdvice
public class AcmeExceptionHandler {

    @ExceptionHandler(AcmeException.class)
    public ResponseEntity<?> acmeExceptionHandler(AcmeException ex, WebRequest request) {
        ErrorBean errorDetails = new ErrorBean(ex.getCode(), ex.getMessage());
        return new ResponseEntity<>(errorDetails, HttpStatus.BAD_REQUEST);
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<?> globalExceptionHandler(Exception ex, WebRequest request) {
        ErrorBean errorDetails = new ErrorBean(HttpStatus.INTERNAL_SERVER_ERROR.value(), ex.getMessage());
        return new ResponseEntity<>(errorDetails, HttpStatus.INTERNAL_SERVER_ERROR);
    }
}